$(document).ready(function(){

    $('#slide1').owlCarousel({
        loop:true,
        margin:10,
        autoplay:true,
        autoplayTimeout:3000,
        autoplaySpeed:2000,
        slideBy:1,
        dots:false,
        responsive:
            {
                0:{
                    items:1
                },
                600:{
                    items:3
                },
                1000:{
                    items:3
                }
            }
        });

        $('#slimg2').owlCarousel({
        rtl:true,
        loop:true,
        margin:10,
        autoplay:true,
        autoplayTimeout:3000,
        autoplaySpeed:2000,
        slideBy:1,
        dots:false,
        responsive:
            {
                0:{
                    items:1
                },
                600:{
                    items:3
                },
                1000:{
                    items:3
                }
            }
        });

});